apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: End-TO-End-CI-CD-Pipeline-using-GitHub-Actions-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: End-TO-End-CI-CD-Pipeline-using-GitHub-Actions
  minReplicas: 1
  maxReplicas: 5
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 50
